## Session-8 Pandas Assignment_8

### 1.) Write a Python program which accepts a list named : randomList = ['a', 0, 2]. Use exception handling using try-catch which gives the output as:

In [1]:
# import module sys to get the type of exception
import sys

randomList = ['a', 0, 2]

for entry in randomList:
    try:
        print("The entry is", entry)
        r = 1/int(entry)
        break
    except:
        print("Oops!",sys.exc_info()[0],"occured.")
        print("Next entry.")
        print()
print("The reciprocal of",entry,"is",r)

The entry is a
Oops! <class 'ValueError'> occured.
Next entry.

The entry is 0
Oops! <class 'ZeroDivisionError'> occured.
Next entry.

The entry is 2
The reciprocal of 2 is 0.5

In [ ]:
#--------------------------------------------------------------#

### 2)Write a Python program to give exception “Array Out of Bound” if the user wants to access the elements beyond the list size (use try and except)

In [2]:
# Python program to handle simple runtime error 
  
a = [1, 2, 3] 
try:  
    print ("Second element = %d" %(a[1]) )
  
    # Throws error since there are only 3 elements in array 
    print("Fourth element = %d" %(a[3]))
    
except IndexError: 
    
    print("Array Out of Bounds")

Second element = 2
Array Out of Bounds

In [ ]:
#--------------------------------------------------------------#

### 3) Write a python module script that contains fib2() method to calculate the Fibonacci series till 1000 and save it as fibo.py.

In [3]:
# Fibonacci numbers module code saved in Anaconda3 Folder

def fib(n):    # write Fibonacci series up to n
    a, b = 0, 1
    while b < n:
        print(b, end=' ')
        a, b = b, a+b
    print()

def fib2(n): # return Fibonacci series up to n
    result = []
    a, b = 0, 1
    while b < n:
        result.append(b)
        a, b = b, a+b
    return result

In [4]:
import fibo # Importing the Fibonacci Module

fib=fibo.fib2(1000)
fib

[1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987]

In [ ]:
#--------------------------------------------------------------#

### 4) Write a python module script that contains ispalindrome() method to calculate the input string as palindrome string or not and save it as palindrome.py.

In [5]:
# Is Palindrome Check module code saved in Anaconda3 Folder
# palindrome or not  
#import math
def isPalindrome(str): 
  
    # Run loop from 0 to len/2  
    for i in range(0, int((len(str)/2))):  
        if str[i] != str[len(str)-i-1]: 
            return False
    return True



  
def isPalindrome2(s): 
    # Calling reverse function 
    rev = s[::-1]  
  
    # Checking if both string are equal or not 
    if (s == rev): 
        return True
    return False

In [6]:
import Palind # Importing the Palindrome Module

pal=Palind.isPalindrome("malayalam")
pal

True

In [7]:
import Palind # Importing the Fibonacci Module

pal=Palind.isPalindrome2("Malayalam")
pal

False

In [ ]:
#--------------------------------------------------------------#b

### 5) Write a program in Python with one class called Cipher. Within the constructor of this class, ask user for a string and store it. Use a static variable, key to store a randomly generated integer between 1 and 50 inclusive. Implement two methods, encrypt and decrypt within this class. Encrypt generates and prints a cipher text using the user-entered string and the key and ecrypt generates decrypted string from ciphertext. The cipher only encrypts alpha and numeric (A-Z, a-z, 0-9). All Symbols, such as - , ; %, remain unencrypted. The cipher text can have special characters. Use generator expression to filter out alpha and numeric characters of the input string and to generate cipher text. Create an instance of this class, encrypt and decrypt back the user entered string.

In [88]:
import numpy as np
from random import randint
class Cipher:
    key = randint(1,50)
    def __init__(self):
        self.plain_text = input("Please enter a string:")
        self.cipher_text = ""
            
    def encrypt(self):
        enc_gen = (chr((ord(x)+self.key-65)%26 + 65) if x.isalnum() and x.isupper() else(chr((ord(x)+self.key-97)%26 + 97) if x.isalnum() and x.islower() else(chr((ord(x)+self.key-48)%10 + 48) if x.isdigit() else x)) for x in self.plain_text)
        self.cipher_text = ''.join(list(enc_gen))
        print("Encrypted String is:"+self.cipher_text)
    
    def decrypt(self):
        dec_gen=(chr((ord(x)-self.key-65)%26 + 65) if x.isalnum() and x.isupper() else (chr((ord(x)-self.key-97)%26 + 97) if x.isalnum() and x.islower() else(chr((ord(x)-self.key-48)%10 + 48) if x.isdigit() else x)) for x in self.plain_text)       
        self.cipher_text = ''.join(list(dec_gen))
        print("Decrypted String is:"+self.cipher_text)

In [89]:
c1=Cipher()
i=input("Select the operation 'D':- Decrypt,'E':- Encrypt")
if (i=="D"):
    c1.decrypt()
elif(i=="E"):
    c1.encrypt()
else:
    print("Invalid Input.Try again")

Please enter a string:VV
Select the operation 'D':- Decrypt,'E':- EncryptD
Decrypted String is:LL

### 6) Get Data from the following link:
http://files.grouplens.org/datasets/movielens/ml-20m.zip
We will be using the following files for this exercise:
ratings.csv : userId,movieId,rating, timestamp
tags.csv : userId,movieId, tag, timestamp
movies.csv : movieId, title, genres

In [2]:
import numpy as np
import pandas as pd
from pandas import DataFrame, Series
import sqlite3 as db

### I. Read the dataset using pandas.

In [18]:
tag=pd.read_csv("C:\\Users\\vmjoseph\\Desktop\\Python Training and Codes\\Acadgild\\Assignments\\Pandas\\ml-20m\\ml-20m\\tags.csv")
tag.head(10)

   userId  movieId               tag   timestamp
0      18     4141       Mark Waters  1240597180
1      65      208         dark hero  1368150078
2      65      353         dark hero  1368150079
3      65      521     noir thriller  1368149983
4      65      592         dark hero  1368150078
5      65      668         bollywood  1368149876
6      65      898  screwball comedy  1368150160
7      65     1248     noir thriller  1368149983
8      65     1391              mars  1368150055
9      65     1617          neo-noir  1368150217

### II. Extract the first row from tags and print its type.

In [4]:
tag1=pd.DataFrame(tag)
tag1.iloc[[0],]

   userId  movieId          tag   timestamp
0      18     4141  Mark Waters  1240597180

In [5]:
import datetime
tag_date=datetime.datetime.fromtimestamp(1240597180 / 1e3)
tag_date

datetime.datetime(1970, 1, 15, 14, 6, 37, 180000)

### III. Extract row 0, 11, 2000 from tags DataFrame.

In [6]:
tag2=tag1.iloc[[0,11,2000],]
tag2

      userId  movieId                tag   timestamp
0         18     4141        Mark Waters  1240597180
11        65     1783      noir thriller  1368149983
2000     910    68554  conspiracy theory  1368043943

### IV. Print index, columns of the DataFrame.

In [7]:
l=[]
for row in tag2.timestamp:
    l.append(datetime.datetime.fromtimestamp(row / 1e3))
print(l, end = " ")

[datetime.datetime(1970, 1, 15, 14, 6, 37, 180000), datetime.datetime(1970, 1, 17, 1, 32, 29, 983000), datetime.datetime(1970, 1, 17, 1, 30, 43, 943000)]

In [8]:
l=[]
for row in tag2.index:
    l.append(row)
print(l, end = " ")

[0, 11, 2000]

In [9]:
l=[]
for col in tag2.columns:
    l.append(col)    
print(l, end = " ")

['userId', 'movieId', 'tag', 'timestamp']

### V. Calculate descriptive statistics for the 'ratings' column of the ratings DataFrame. Verify using describe().

In [9]:
rat=pd.read_csv("C:\\Users\\vmjoseph\\Desktop\\Python Training and Codes\\Acadgild\\Assignments\\Pandas\\ml-20m\\ml-20m\\ratings.csv")
rat.head(10)

   userId  movieId  rating   timestamp
0       1        2     3.5  1112486027
1       1       29     3.5  1112484676
2       1       32     3.5  1112484819
3       1       47     3.5  1112484727
4       1       50     3.5  1112484580
5       1      112     3.5  1094785740
6       1      151     4.0  1094785734
7       1      223     4.0  1112485573
8       1      253     4.0  1112484940
9       1      260     4.0  1112484826

In [11]:
rat1=pd.DataFrame(rat)
r1=round(rat1.rating.mean(),2)
r2=round(rat1.rating.std(),2)
r3=round(rat1.rating.min(),2)
r4=round(rat1.rating.max(),2)
r5=round(rat1.rating.count(),2)
r6=rat1.rating.quantile([.1, .25, .5, .75],)
l=[r1,r2,r3,r4,r5,r6]
print(l)

[3.53, 1.05, 0.5, 5.0, 20000263, 0.10    2.0
0.25    3.0
0.50    3.5
0.75    4.0
Name: rating, dtype: float64]

In [12]:
rat1.rating.describe()

count    2.000026e+07
mean     3.525529e+00
std      1.051989e+00
min      5.000000e-01
25%      3.000000e+00
50%      3.500000e+00
75%      4.000000e+00
max      5.000000e+00
Name: rating, dtype: float64

### VI. Filter out ratings with rating > 5

In [13]:
rat1[rat1["rating"]>5]

Empty DataFrame
Columns: [userId, movieId, rating, timestamp]
Index: []

### VII. Find how many null values, missing values are present. Deal with them. Print out how many rows have been modified.

In [14]:
# No rows or columns having missing values 
rat1.isnull().any()

userId       False
movieId      False
rating       False
timestamp    False
dtype: bool

### VIII. Filter out movies from the movies DataFrame that are of type 'Animation'.

In [8]:
mov=pd.read_csv("C:\\Users\\vmjoseph\\Desktop\\Python Training and Codes\\Acadgild\\Assignments\\Pandas\\ml-20m\\ml-20m\\movies.csv")
mov1=pd.DataFrame(mov)
mov.head(10)

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
5,6,Heat (1995),Action|Crime|Thriller
6,7,Sabrina (1995),Comedy|Romance
7,8,Tom and Huck (1995),Adventure|Children
8,9,Sudden Death (1995),Action
9,10,GoldenEye (1995),Action|Adventure|Thriller

In [16]:
import numpy as np
import pandas as pd
from pandas import DataFrame, Series
import sqlite3 as db

In [5]:
from pandasql import sqldf #Allows to access dataframe in SQL query style

In [6]:
pysqldf = lambda q: sqldf(q, globals())

In [14]:
pysqldf("""SELECT * FROM mov1 as A
         where A.genres like '%Animation%';""")

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,13,Balto (1995),Adventure|Animation|Children
2,48,Pocahontas (1995),Animation|Children|Drama|Musical|Romance
3,239,"Goofy Movie, A (1995)",Animation|Children|Comedy|Romance
4,244,Gumby: The Movie (1995),Animation|Children
5,313,"Swan Princess, The (1994)",Animation|Children
6,364,"Lion King, The (1994)",Adventure|Animation|Children|Drama|Musical|IMAX
7,392,"Secret Adventures of Tom Thumb, The (1993)",Adventure|Animation
8,551,"Nightmare Before Christmas, The (1993)",Animation|Children|Fantasy|Musical
9,558,"Pagemaster, The (1994)",Action|Adventure|Animation|Children|Fantasy
10,588,Aladdin (1992),Adventure|Animation|Children|Comedy|Musical
11,594,Snow White and the Seven Dwarfs (1937),Animation|Children|Drama|Fantasy|Musical
12,595,Beauty and the Beast (1991),Animation|Children|Fantasy|Musical|Romance|IMAX
13,596,Pinocchio (1940),Animation|Children|Fantasy|Musical
14,610,Heavy Metal (1981),Action|Adventure|Animation|Horror|Sci-Fi
15,616,"Aristocats, The (1970)",Animation|Children
16,631,All Dogs Go to Heaven 2 (1996),Adventure|Animation|Children|Fantasy|Musical|R...
17,661,James and the Giant Peach (1996),Adventure|Animation|Children|Fantasy|Musical
18,673,Space Jam (1996),Adventure|Animation|Children|Comedy|Fantasy|Sc...
19,709,Oliver & Company (1988),Adventure|Animation|Children|Comedy|Musical
20,720,Wallace & Gromit: The Best of Aardman Animatio...,Adventure|Animation|Comedy
21,741,Ghost in the Shell (Kôkaku kidôtai) (1995),Animation|Sci-Fi
22,745,Wallace & Gromit: A Close Shave (1995),Animation|Children|Comedy
23,783,"Hunchback of Notre Dame, The (1996)",Animation|Children|Drama|Musical|Romance
24,888,Land Before Time III: The Time of the Great Gi...,Adventure|Animation|Children|Musical
25,1022,Cinderella (1950),Animation|Children|Fantasy|Musical|Romance
26,1023,Winnie the Pooh and the Blustery Day (1968),Animation|Children|Musical
27,1024,"Three Caballeros, The (1945)",Animation|Children|Musical
28,1025,"Sword in the Stone, The (1963)",Animation|Children|Fantasy|Musical
29,1029,Dumbo (1941),Animation|Children|Drama|Musical
...,...,...,...
997,129830,Animals United (2011),Animation|Children|Comedy
998,129834,Tom and Jerry: The Lost Dragon (2014),Animation|Children|Comedy
999,129859,Mardock Scramble: The Second Combustion (2011),Animation|Sci-Fi
1000,130034,Stand by Me Doraemon (2014),Animation|Children|Drama|Fantasy
1001,130075,Frozen Fever (2015),Adventure|Animation
1002,130394,The Mascot (1934),Animation
1003,130402,Cardcaptor Sakura: The Sealed Card (2000),Adventure|Animation|Comedy|Fantasy|Romance
1004,130506,Berserk: The Golden Age Arc 2 - The Battle for...,Action|Animation|Fantasy
1005,130508,Berserk: The Golden Age Arc - The Egg of the K...,Action|Adventure|Animation|Fantasy|Horror
1006,130510,Berserk: The Golden Age Arc 3 - Descent (2013),Action|Animation|Fantasy
1007,130518,The Amazing Screw-On Head (2006),Action|Adventure|Animation|Comedy|Sci-Fi
1008,130520,Home (2015),Animation|Children|Comedy|Fantasy|Sci-Fi
1009,130522,The Brave Little Toaster Goes to Mars (1998),Animation|Children
1010,130644,The Garden of Sinners - Chapter 5: Paradox Par...,Animation
1011,131058,Santa's Apprentice (2010),Animation|Children
1012,131066,Ronal the Barbarian (2011),Adventure|Animation|Fantasy
1013,131080,Cinderella III: A Twist in Time (2007),Animation|Children|Fantasy|Romance
1014,131086,The Little Polar Bear: Lars and the Little Tig...,Animation|Children
1015,131092,"Mickey, Donald, Goofy: The Three Musketeers (2...",Adventure|Animation|Children|Comedy
1016,131094,Rudolph the Red-Nosed Reindeer: The Movie (1998),Animation|Children
1017,131098,Saving Santa (2013),Animation|Children|Comedy
1018,131102,Lucky Luke: The Ballad of the Daltons (1978),Animation|Children|Comedy|Western
1019,131106,Casper's Haunted Christmas (2000),Animation|Children
1020,131120,Superstar Goofy (1991),Animation|Children|Comedy
1021,131130,Tom and Jerry: A Nutcracker Tale (2007),Animation|Comedy
1022,131132,Kleines Arschloch - Der Film (1997),Animation|Comedy
1023,131144,Werner - Das muss kesseln!!! (1996),Animation|Comedy
1024,131146,Werner - Volles Rooäää (1999),Animation|Comedy
1025,131243,Werner - Gekotzt wird später (2003),Animation|Comedy
1026,131248,Brother Bear 2 (2006),Adventure|Animation|Children|Comedy|Fantasy

### IX. Find the average rating of movies.

In [15]:
pysqldf("""SELECT A.movieId,A.title,Avg(rating) FROM mov1 as A
         inner join rat1 as B ON A.movieId=B.movieId
         group by A.movieId,A.title ;""")

       movieId                                              title  Avg(rating)
0            1                                   Toy Story (1995)     3.921240
1            2                                     Jumanji (1995)     3.211977
2            3                            Grumpier Old Men (1995)     3.151040
3            4                           Waiting to Exhale (1995)     2.861393
4            5                 Father of the Bride Part II (1995)     3.064592
5            6                                        Heat (1995)     3.834930
6            7                                     Sabrina (1995)     3.366484
7            8                                Tom and Huck (1995)     3.142049
8            9                                Sudden Death (1995)     3.004924
9           10                                   GoldenEye (1995)     3.430029
10          11                     American President, The (1995)     3.667713
11          12                 Dracula: Dead and Loving It (1995)     2.619766
12          13                                       Balto (1995)     3.272416
13          14                                       Nixon (1995)     3.432082
14          15                            Cutthroat Island (1995)     2.721993
15          16                                      Casino (1995)     3.787455
16          17                       Sense and Sensibility (1995)     3.968573
17          18                                  Four Rooms (1995)     3.373631
18          19              Ace Ventura: When Nature Calls (1995)     2.607412
19          20                                 Money Train (1995)     2.880754
20          21                                  Get Shorty (1995)     3.581689
21          22                                     Copycat (1995)     3.319400
22          23                                   Assassins (1995)     3.148235
23          24                                      Powder (1995)     3.199849
24          25                           Leaving Las Vegas (1995)     3.689510
25          26                                     Othello (1995)     3.628857
26          27                                Now and Then (1995)     3.413520
27          28                                  Persuasion (1995)     4.057546
28          29  City of Lost Children, The (Cité des enfants p...     3.952230
29          30  Shanghai Triad (Yao a yao yao dao waipo qiao) ...     3.633880
...        ...                                                ...          ...
26714   131146                      Werner - Volles Rooäää (1999)     4.000000
26715   131148                                  What A Man (2011)     4.000000
26716   131150         7 Dwarves: The Forest Is Not Enough (2006)     4.000000
26717   131152                                 The Fat Spy (1966)     0.500000
26718   131154  Die Bademeister – Weiber, saufen, Leben retten...     3.500000
26719   131156                         Ants in the Pants 2 (2002)     4.000000
26720   131158                                Manta, Manta (1991)     4.000000
26721   131160                  Oscar and the Lady in Pink (2009)     4.000000
26722   131162                      Por un puñado de besos (2014)     2.000000
26723   131164                               Vietnam in HD (2011)     4.000000
26724   131166                                  WWII IN HD (2009)     4.000000
26725   131168                                     Phoenix (2014)     3.500000
26726   131170                                   Parallels (2015)     3.500000
26727   131172                              Closed Curtain (2013)     1.000000
26728   131174                                   Gentlemen (2014)     3.500000
26729   131176                             A Second Chance (2014)     4.500000
26730   131180                     Dead Rising: Watchtower (2015)     2.500000
26731   131231                                     Standby (2014)     3.500000
26732   131237                         What Men Talk About (2010)     3.000000
26733   131239                          Three Quarter Moon (2011)     4.000000
26734   131241                           Ants in the Pants (2000)     4.000000
26735   131243                Werner - Gekotzt wird später (2003)     4.000000
26736   131248                              Brother Bear 2 (2006)     4.000000
26737   131250                              No More School (2000)     4.000000
26738   131252  Forklift Driver Klaus: The First Day on the Jo...     4.000000
26739   131254                       Kein Bund für's Leben (2007)     4.000000
26740   131256                      Feuer, Eis & Dosenbier (2002)     4.000000
26741   131258                                 The Pirates (2014)     2.500000
26742   131260                                Rentun Ruusu (2001)     3.000000
26743   131262                                   Innocence (2014)     4.000000

[26744 rows x 3 columns]

### X. Perform an inner join of movies and tags based on movieId.

In [20]:
mov1=pd.DataFrame(mov)
tag1=pd.DataFrame(tag)
mov_tag=pd.merge(mov1,tag1,how='inner',on='movieId')
mov_tag

,movieId,title,genres,userId,tag,timestamp
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1644,Watched,1417736680
1,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1741,computer animation,1183903155
2,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1741,Disney animated feature,1183933307
3,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1741,Pixar animation,1183934770
4,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1741,TÃ©a Leoni does not star in this movie,1245093573
5,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,2299,Pixar,1403306852
6,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,3596,animation,1290312028
7,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,3596,family,1290312032
8,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,3596,Tom Hanks,1290312036
9,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,6233,Pixar,1387079572
10,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,6233,witty,1387079576
11,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,8219,Pixar,1159534063
12,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,10616,adventure,1277357423
13,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,10616,animated,1277357419
14,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,10616,animation,1277357417
15,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,10616,clever,1277357438
16,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,10616,comedy,1277357433
17,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,10616,computer animation,1277357405
18,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,10616,family,1277357449
19,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,10616,fantasy,1277357430
20,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,10616,Tom Hanks,1277357411
21,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,11081,bright,1173304070
22,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,11081,DARING RESCUES,1173304095
23,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,11081,fanciful,1173304058
24,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,11081,HEROIC MISSION,1173304102
25,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,11081,humorous,1173304049
26,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,11081,light,1173304062
27,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,11081,rousing,1173304074
28,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,11081,TOYS COME TO LIFE,1173304091
29,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,11081,UNLIKELY FRIENDSHIPS,1173304106
...,...,...,...,...,...,...
465534,131015,Hellgate (2011),Horror|Thriller,25978,Cary Elwes,1427585540
465535,131015,Hellgate (2011),Horror|Thriller,25978,Demons,1427585566
465536,131015,Hellgate (2011),Horror|Thriller,25978,Exorcism,1427585551
465537,131015,Hellgate (2011),Horror|Thriller,25978,Ghosts,1427585546
465538,131015,Hellgate (2011),Horror|Thriller,25978,Monks,1427585560
465539,131015,Hellgate (2011),Horror|Thriller,25978,nurse,1427585621
465540,131015,Hellgate (2011),Horror|Thriller,25978,psychic,1427585613
465541,131015,Hellgate (2011),Horror|Thriller,25978,slow,1427585575
465542,131015,Hellgate (2011),Horror|Thriller,25978,special effects,1427585690
465543,131015,Hellgate (2011),Horror|Thriller,25978,surfing,1427585592
465544,131015,Hellgate (2011),Horror|Thriller,25978,Thailand,1427585543
465545,131015,Hellgate (2011),Horror|Thriller,25978,William Hurt,1427585696
465546,131031,La liga no es cosa de hombres (1972),(no genres listed),33323,Barcelona,1427641562
465547,131031,La liga no es cosa de hombres (1972),(no genres listed),33323,exploitation,1427641559
465548,131031,La liga no es cosa de hombres (1972),(no genres listed),33323,female football,1427641577
465549,131031,La liga no es cosa de hombres (1972),(no genres listed),33323,football,1427641548
465550,131031,La liga no es cosa de hombres (1972),(no genres listed),33323,Rome,1427641564
465551,131031,La liga no es cosa de hombres (1972),(no genres listed),33323,shorts,1427641571
465552,131031,La liga no es cosa de hombres (1972),(no genres listed),33323,soccer,1427641556
465553,131031,La liga no es cosa de hombres (1972),(no genres listed),33323,transvestite,1427641589
465554,131054,Dinotopia: Quest for the Ruby Sunstone (2005),Children|Fantasy|Sci-Fi,88144,dinosaurs,1427654430
465555,131082,Playground (2009),(no genres listed),92885,documentary,1427654757
465556,131082,Playground (2009),(no genres listed),92885,Yoshitomo Nara,1427654856
465557,131164,Vietnam in HD (2011),War,54560,Vietnam War,1427667401
465558,131170,Parallels (2015),Sci-Fi,88738,alternate reality,1427732804
465559,131258,The Pirates (2014),Adventure,28906,bandits,1427745421
465560,131258,The Pirates (2014),Adventure,28906,Korea,1427745512
465561,131258,The Pirates (2014),Adventure,28906,mutiny,1427745542
465562,131258,The Pirates (2014),Adventure,28906,pirates,1427745419
465563,131258,The Pirates (2014),Adventure,28906,whale,1427745432

### XI. Print out the 5 movies that belong to the Comedy genre and have rating greater than 4.

In [12]:
# Using Sqldf to 

pysqldf(""" Select * from
         (SELECT A.movieId,A.title,Avg(B.rating) FROM mov1 as A
         inner join rat1 as B ON A.movieId=B.movieId
         where A.genres like '%Comedy%'
         group by A.movieId 
         Having Avg(B.rating)>4 
         order by Avg(B.rating)Desc)LIMIT 5 ;""")

   movieId                                            title  Avg(B.rating)
0    86055      Foster Brothers, The (Süt kardesler) (1976)            5.0
1    99243                            Parasites, Les (1999)            5.0
2   104317  Flight of the Conchords: A Texan Odyssey (2006)            5.0
3   107434                     Diplomatic Immunity (2009– )            5.0
4   109715                            Inquire Within (2012)            5.0

### XIII. Extract year from title e.g. (1995).

In [87]:
mov1=mov1.drop([31])
new1=mov1['title'].str.split('(',expand=True)
new1.columns = ['Title', 'Year','1','2','3','4']
new3=new1['Year'].str.split(')',expand=True)
new3.columns=['Year','1']
mov3=pd.concat([new1['Title'],new3['Year']],axis=1)
mov3

                                                  Title  Year
0                                            Toy Story   1995
1                                              Jumanji   1995
2                                     Grumpier Old Men   1995
3                                    Waiting to Exhale   1995
4                          Father of the Bride Part II   1995
5                                                 Heat   1995
6                                              Sabrina   1995
7                                         Tom and Huck   1995
8                                         Sudden Death   1995
9                                            GoldenEye   1995
10                             American President, The   1995
11                         Dracula: Dead and Loving It   1995
12                                               Balto   1995
13                                               Nixon   1995
14                                    Cutthroat Island   1995
15                                              Casino   1995
16                               Sense and Sensibility   1995
17                                          Four Rooms   1995
18                      Ace Ventura: When Nature Calls   1995
19                                         Money Train   1995
20                                          Get Shorty   1995
21                                             Copycat   1995
22                                           Assassins   1995
23                                              Powder   1995
24                                   Leaving Las Vegas   1995
25                                             Othello   1995
26                                        Now and Then   1995
27                                          Persuasion   1995
30                                     Dangerous Minds   1995
32                                    Wings of Courage   1995
...                                                 ...   ...
27248                           Werner - Volles Rooäää   1999
27249                                       What A Man   2011
27250              7 Dwarves: The Forest Is Not Enough   2006
27251                                      The Fat Spy   1966
27252   Die Bademeister – Weiber, saufen, Leben retten   1999
27253                              Ants in the Pants 2   2002
27254                                     Manta, Manta   1991
27255                       Oscar and the Lady in Pink   2009
27256                           Por un puñado de besos   2014
27257                                    Vietnam in HD   2011
27258                                       WWII IN HD   2009
27259                                          Phoenix   2014
27260                                        Parallels   2015
27261                                   Closed Curtain   2013
27262                                        Gentlemen   2014
27263                                  A Second Chance   2014
27264                          Dead Rising: Watchtower   2015
27265                                          Standby   2014
27266                              What Men Talk About   2010
27267                               Three Quarter Moon   2011
27268                                Ants in the Pants   2000
27269                     Werner - Gekotzt wird später   2003
27270                                   Brother Bear 2   2006
27271                                   No More School   2000
27272  Forklift Driver Klaus: The First Day on the Job   2001
27273                            Kein Bund für's Leben   2007
27274                           Feuer, Eis & Dosenbier   2002
27275                                      The Pirates   2014
27276                                     Rentun Ruusu   2001
27277                                        Innocence   2014

[27275 rows x 2 columns]

### XII. Split 'genres' into multiple columns.

In [23]:
new = mov1['genres'].str.split('|',expand=True)
new

,0,1,2,3,4,5,6,7,8,9
0,Adventure,Animation,Children,Comedy,Fantasy,None,None,None,None,None
1,Adventure,Children,Fantasy,None,None,None,None,None,None,None
2,Comedy,Romance,None,None,None,None,None,None,None,None
3,Comedy,Drama,Romance,None,None,None,None,None,None,None
4,Comedy,None,None,None,None,None,None,None,None,None
5,Action,Crime,Thriller,None,None,None,None,None,None,None
6,Comedy,Romance,None,None,None,None,None,None,None,None
7,Adventure,Children,None,None,None,None,None,None,None,None
8,Action,None,None,None,None,None,None,None,None,None
9,Action,Adventure,Thriller,None,None,None,None,None,None,None
10,Comedy,Drama,Romance,None,None,None,None,None,None,None
11,Comedy,Horror,None,None,None,None,None,None,None,None
12,Adventure,Animation,Children,None,None,None,None,None,None,None
13,Drama,None,None,None,None,None,None,None,None,None
14,Action,Adventure,Romance,None,None,None,None,None,None,None
15,Crime,Drama,None,None,None,None,None,None,None,None
16,Drama,Romance,None,None,None,None,None,None,None,None
17,Comedy,None,None,None,None,None,None,None,None,None
18,Comedy,None,None,None,None,None,None,None,None,None
19,Action,Comedy,Crime,Drama,Thriller,None,None,None,None,None
20,Comedy,Crime,Thriller,None,None,None,None,None,None,None
21,Crime,Drama,Horror,Mystery,Thriller,None,None,None,None,None
22,Action,Crime,Thriller,None,None,None,None,None,None,None
23,Drama,Sci-Fi,None,None,None,None,None,None,None,None
24,Drama,Romance,None,None,None,None,None,None,None,None
25,Drama,None,None,None,None,None,None,None,None,None
26,Children,Drama,None,None,None,None,None,None,None,None
27,Drama,Romance,None,None,None,None,None,None,None,None
28,Adventure,Drama,Fantasy,Mystery,Sci-Fi,None,None,None,None,None
29,Crime,Drama,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...
27248,Animation,Comedy,None,None,None,None,None,None,None,None
27249,Comedy,Romance,None,None,None,None,None,None,None,None
27250,Comedy,None,None,None,None,None,None,None,None,None
27251,Comedy,None,None,None,None,None,None,None,None,None
27252,Comedy,None,None,None,None,None,None,None,None,None
27253,Comedy,None,None,None,None,None,None,None,None,None
27254,Comedy,None,None,None,None,None,None,None,None,None
27255,Drama,None,None,None,None,None,None,None,None,None
27256,Drama,Romance,None,None,None,None,None,None,None,None
27257,War,None,None,None,None,None,None,None,None,None
27258,(no genres listed),None,None,None,None,None,None,None,None,None
27259,Drama,None,None,None,None,None,None,None,None,None
27260,Sci-Fi,None,None,None,None,None,None,None,None,None
27261,(no genres listed),None,None,None,None,None,None,None,None,None
27262,Drama,Romance,Thriller,None,None,None,None,None,None,None
27263,Drama,None,None,None,None,None,None,None,None,None
27264,Action,Horror,Thriller,None,None,None,None,None,None,None
27265,Comedy,Romance,None,None,None,None,None,None,None,None
27266,Comedy,None,None,None,None,None,None,None,None,None
27267,Comedy,Drama,None,None,None,None,None,None,None,None
27268,Comedy,Romance,None,None,None,None,None,None,None,None
27269,Animation,Comedy,None,None,None,None,None,None,None,None
27270,Adventure,Animation,Children,Comedy,Fantasy,None,None,None,None,None
27271,Comedy,None,None,None,None,None,None,None,None,None
27272,Comedy,Horror,None,None,None,None,None,None,None,None
27273,Comedy,None,None,None,None,None,None,None,None,None
27274,Comedy,None,None,None,None,None,None,None,None,None
27275,Adventure,None,None,None,None,None,None,None,None,None
27276,(no genres listed),None,None,None,None,None,None,None,None,None
27277,Adventure,Fantasy,Horror,None,None,None,None,None,None,None

### XIV. Select rows based on timestamps later than 2015-02-01.

In [24]:
#1422748800 is the integer value corresponding to time stamp 2015-02-01
tag1[tag1["timestamp"]>1422748800]

        userId  movieId                       tag   timestamp
301        318      260                     1970s  1424472169
302        318      260                   fantasy  1424472169
303        318      260                    sci-fi  1424472169
304        318   115149                    Action  1424534310
305        318   115149                   Revenge  1424534283
306        318   115149              Willem Dafoe  1424534383
324        342      318                masterplan  1423424898
326        342      318             prison escape  1423424898
327        342      318                redemption  1423424898
589        342   108190           based on a book  1426978115
590        342   108190                  dystopia  1426978076
1018       370     6975  breaking the fourth wall  1425242234
1019       370    27592                   violent  1425241975
2203       969       97            class conflict  1426754226
2204       969      288                  mindfuck  1426752631
2205       969      288                  paranoid  1426752639
2206       969      288               psychedelic  1426752634
2207       969     1263       american propaganda  1426753995
2208       969     3742            class conflict  1426753876
2209       969     3742                   Classic  1426754311
2210       969     3742                Propaganda  1426754337
2211       969     4848               Atmospheric  1426752575
2212       969     4848                      dark  1426752581
2213       969     4848                  Mindfuck  1426752569
2214       969     6530            claustrophobic  1426753144
2215       969     6530            mental illness  1426751285
2216       969     6530                   suicide  1426751289
2217       969     8950                depressing  1426749117
2218       969     8950               psychodrama  1426752695
2219       969     8950             schizophrenia  1426752689
...        ...      ...                       ...         ...
461895  137227   120222         horribly animated  1422821079
461896  137227   120222              nazi imagery  1422821051
461897  137227   120222                    racist  1422821047
461898  137227   120222        racist stereotypes  1422821071
462190  137249      296               influential  1423437040
462191  137249      296                  neo-noir  1423437040
462192  137249      296         quentin tarantino  1423437040
462195  137277   110052     marcello mastroianni,  1422925214
462979  137924    46855                 Criterion  1427722627
462980  137924    46855         French Resistance  1427722622
462981  137924    46855              World War II  1427722614
463004  138063     4355                    Hockey  1424230535
463005  138063   108160                    Hockey  1424230501
463504  138103    67894                   finnish  1423255773
463509  138103    69442                   finnish  1423255750
463544  138103    73501                   finnish  1423255756
463545  138103    74681                   finnish  1423255760
463573  138103    84553                   finnish  1423255764
464786  138301    52042                 espionage  1426032479
464787  138301    52042       resistance movement  1426032481
464788  138301    52042              World War II  1426032485
464958  138301   109487                 ambitious  1423178287
464959  138301   109487                atmosphere  1423178302
464960  138301   109487                plot holes  1423178186
464961  138301   109487                    sci-fi  1423178227
464962  138301   109487           science fiction  1423178255
464963  138301   109487            Self-Indulgent  1423178219
464964  138301   109487                     space  1423178343
464965  138301   109487        visually appealing  1423178319
464966  138301   109487          wasted potential  1423178212

[12130 rows x 4 columns]

### XV. Sort the tags DataFrame based on timestamp.

In [25]:
tag1.sort_values("timestamp", axis = 0, ascending =False, 
                 inplace = True, na_position ='last')
tag1

        userId  movieId                              tag   timestamp
339178  102853   115149                    russian mafia  1427771352
158780   46072     6058                      premonition  1427760764
158763   46072     3409                      premonition  1427760726
288375   87797      215                           Vienna  1427755801
290535   88044   106782                        profanity  1427754096
290527   88044   106782                            crime  1427753921
290526   88044   106782                           Amoral  1427753913
290531   88044   106782                       Jonah Hill  1427753849
290530   88044   106782                       inaccurate  1427753806
290528   88044   106782  Economically Illiterate Writers  1427753739
290533   88044   106782                Left-Wing Writers  1427753621
290532   88044   106782             Left-Wing Propaganda  1427753266
290529   88044   106782                             ENFP  1427753147
290534   88044   106782                           Orgies  1427753111
290536   88044   106782              unsatisfying ending  1427753000
392904  122523     5004                            party  1427752292
392905  122523     5004                              USA  1427752289
150872   42640   115122                      dark comedy  1427748808
150871   42640   115122                           comedy  1427748797
150873   42640   115122                     mockumentary  1427748778
400106  123297     4573                              CLV  1427747462
405123  123297   118722                              CLV  1427747321
401017  123297     6481                              CLV  1427747220
400993  123297     6419                              CLV  1427746864
399877  123297     4211                              CLV  1427746709
405155  123297   128642                              CLV  1427746337
119989   28906   115149                           cheesy  1427746074
119993   28906   115149                     over the top  1427746060
119991   28906   115149                    lack of story  1427746053
119997   28906   115149                          violent  1427746031
...        ...      ...                              ...         ...
81445    20513    36529                              usa  1136242623
68916    16050     6898                          british  1136039368
68918    16050     6898                            harsh  1136039368
68917    16050     6898                            drugs  1136039368
68919    16050     7060                        christian  1136039301
68922    16050     7060                        religious  1136039301
68920    16050     7060                           kitsch  1136039301
68921    16050     7060                          musical  1136039301
68924    16050    38886                         eighties  1136036612
68928    16050    38886                             twee  1136036612
68926    16050    38886                         new york  1136036612
68927    16050    38886                        overrated  1136036612
68925    16050    38886                           family  1136036612
15926     3797     8573             Nonlinear Surrealism  1135936223
256663   75141     4642                         Terrible  1135688095
15903     3797      110                        overrated  1135589075
333944  100371     6016                           brazil  1135429520
333930  100371     2329                    edward norton  1135429508
333931  100371     2329                     fuckoff nazi  1135429508
333933  100371     2858                     kevin spacey  1135429466
333920  100371       32                     bruce willis  1135429442
333936  100371     4011                        brad pitt  1135429431
333937  100371     4011                      guy ritchie  1135429431
333922  100371       47                   morgan freeman  1135429412
333921  100371       47                        brad pitt  1135429412
333939  100371     5004                    peter sellers  1135429399
333923  100371     1193                   jack nicholson  1135429371
333924  100371     1206                  stanley kubrick  1135429248
333927  100371     1732                    coen brothers  1135429236
333932  100371     2788                     monty python  1135429210

[465564 rows x 4 columns]

In [ ]:
#---------------------------------------------------------#